modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Drop-the-Rock/issues"

[[mods]]
modId="droptherock"
version="1.19.2-1.0"
displayName="Drop the Rock"
displayURL="https://www.curseforge.com/minecraft/mc-mods/drop-the-rock-no-tree-punching-compat"
logoFile="logo.png"
credits=""
authors="Samlegamer"

description='''
Compatibility for No Tree Punching this mod allows you to drop rocks instead of cobblestone, like in No Tree Punching 1.12 finally.

- Support Oh The Biomes You'll Go!
- Support Biomes O' Plenty
- Support Quark
'''

[[dependencies.droptherock]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.droptherock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.droptherock]]
    modId = "notreepunching"
    mandatory = true
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.droptherock]]
    modId = "byg"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.droptherock]]
    modId = "quark"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"

[[dependencies.droptherock]]
    modId = "biomesoplenty"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"