modLoader="javafml"
loaderVersion="[40,)"

license="${mod_license}"
issueTrackerURL="https://github.com/Samlegamer/Drop-the-Rock/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
wiki="https://github.com/Samlegamer/Drop-the-Rock/wiki"
displayURL="https://www.curseforge.com/minecraft/mc-mods/drop-the-rock-no-tree-punching-compat" #optional
logoFile="logo_droptherock.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId = "notreepunching"
mandatory = true
ordering = "AFTER"
versionRange = "NONE"

[[dependencies.${mod_id}]]
modId = "byg"
mandatory = false
ordering = "AFTER"
versionRange = "NONE"

[[dependencies.${mod_id}]]
modId = "quark"
mandatory = false
ordering = "AFTER"
versionRange = "NONE"

[[dependencies.${mod_id}]]
modId = "biomesoplenty"
mandatory = false
ordering = "AFTER"
versionRange = "NONE"